version: '3'

services:
  machineapi:
    container_name: machine_api
    image: flsi/machine-api:1.1
    restart: on-failure
    depends_on:
      - mongodb
    environment:
      - DATABASE-HOST=mongodb
      - DATABASE-PORT=27019
      - DATABASE-USERNAME=machineapi_user
      - DATABASE-PASSWORD=1980
    ports:
      - 8115:8115

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27019:27017"
    healthcheck:
      test: ["CMD", "/docker-healthcheck"]
      timeout: 10s
      interval: 10s
      retries: 10
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d/
      - ./scripts/docker-healthcheck:/docker-healthcheck:ro
    networks:
      - flexlink
    restart: always
    command: 'mongod --bind_ip 0.0.0.0'

networks:
  flexlink:
    external: false
